
const userTypeAction = {

    GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
    EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNIN_FAILURE: 'SIGNIN_FAILURE',

}

export default userTypeAction;