const CartType = {
  CART_TOGGLE: "CART_TOGGLE",
  ADD_ITEMS_TO_CART: "ADD_ITEMS_TO_CART",
  REMOVE_ITEMS_BY_ID: "REMOVE_ITEMS_BY_ID",
  DECREASE_ITEMS_BY_ID: "DECREASE_ITEMS_BY_ID",
};

export default CartType;
